# 🚀 **Practical No. 16: Create Confusion Matrix and Evaluate Model Performance Metrics Using Python**

> 🎯 **Laboratory Learning Outcome (LLO) 16.1:**  Implement a confusion matrix and calculate performance metrics to evaluate classification model quality.

> 📘 **Course Outcome (CO):** CO5

> 💻 **Title:** Write Program to Create Confusion Matrix and Calculate Different Measures to Quantify Model Quality

> 🌐 **Domain:** Artificial Intelligence and Machine Learning  

> 📚 **Subject:** AI & ML ALGORITHM  

> 🐍 **Language:** Python


> 📖 **Description:**
A **Confusion Matrix** is a performance evaluation tool used in **classification problems** in Machine Learning. It provides a summary of prediction results by comparing actual and predicted values. <br><br>
📊 It is a table that consists of:
> - **True Positives (TP)**: Correctly predicted positive class  
> - **True Negatives (TN)**: Correctly predicted negative class  
> - **False Positives (FP)**: Incorrectly predicted positive class  
> - **False Negatives (FN)**: Incorrectly predicted negative class  


---

### Import Library

In [ ]:
import kagglehub
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import confusion_matrix, classification_report, accuracy_score

### Import Dataset

In [ ]:
path = kagglehub.dataset_download("ganeshborkar31/car-dekho")

Downloading from https://www.kaggle.com/api/v1/datasets/download/ganeshborkar31/car-dekho?dataset_version_number=1...

100%|██████████| 55.8k/55.8k [00:00<00:00, 20.0MB/s]

Extracting files...

In [ ]:
df = pd.read_csv(f"{path}/cardekho.csv")

In [ ]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

### Label encoding

In [ ]:
label_encoder = LabelEncoder()

In [ ]:
df['fuel'] = label_encoder.fit_transform(df['fuel'])
df['seller_type'] = label_encoder.fit_transform(df['seller_type'])
df['transmission'] = label_encoder.fit_transform(df['transmission'])
df['owner'] = label_encoder.fit_transform(df['owner'])

In [ ]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,4,1,1,0
1,Maruti Wagon R LXI Minor,2007,135000,50000,4,1,1,0
2,Hyundai Verna 1.6 SX,2012,600000,100000,1,1,1,0
3,Datsun RediGO T Option,2017,250000,46000,4,1,1,0
4,Honda Amaze VX i-DTEC,2014,450000,141000,1,1,1,2

# Categorical target for classification

In [ ]:
df['price_category'] = pd.cut(df['selling_price'], bins=3, labels=['Low', 'Medium', 'High'])

### Define X and Y

In [ ]:
features = ['year', 'km_driven', 'fuel', 'seller_type', 'transmission', 'owner']
target = 'price_category'

In [ ]:
X = df[features]
y = df[target]

> Shape of X and y

In [ ]:
print("Shape of X:", X.shape)
print("Shape of Y:", y.shape)

Shape of X: (4340, 6)
Shape of Y: (4340,)

### Split into train test
> test size 20%

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=50)

> Shape of test train

In [ ]:
print('x_train:', X_train.shape, 'y_train:', y_train.shape)
print('x_test: ', X_test.shape,  'y_test: ', y_test.shape)

x_train: (3472, 6) y_train: (3472,)
x_test:  (868, 6) y_test:  (868,)

### Define Algorithm

> K Means

In [ ]:
model = DecisionTreeClassifier(random_state=42)

DecisionTreeClassifier(random_state=42)

### Fit algorithm

In [ ]:
model.fit(X_train, y_train)

DecisionTreeClassifier(random_state=42)

### Predict result

In [ ]:
y_pred = model.predict(X_test)

### Check score

In [ ]:
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[852  11]
 [  0   5]]